// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGtBZ01cf7lLGwDljupC7fJFAPedvfSk',
    appId: '1:308437145477:web:26e1789ad75f9d114356ec',
    messagingSenderId: '308437145477',
    projectId: 'iba-app-9d4d4',
    authDomain: 'iba-app-9d4d4.firebaseapp.com',
    storageBucket: 'iba-app-9d4d4.appspot.com',
    measurementId: 'G-DNHMYZDSQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2jBMoWSzIxpNh1B7J9Kr33FEfVZFw4H4',
    appId: '1:308437145477:android:f8c0e38580d23a6a4356ec',
    messagingSenderId: '308437145477',
    projectId: 'iba-app-9d4d4',
    storageBucket: 'iba-app-9d4d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6v955zBEPwuldjHfvzIhVQ3mALczW9g',
    appId: '1:308437145477:ios:6d91d92cd45313554356ec',
    messagingSenderId: '308437145477',
    projectId: 'iba-app-9d4d4',
    storageBucket: 'iba-app-9d4d4.appspot.com',
    iosBundleId: 'com.example.ibaApp',
  );
}
